### ISSUE TITLE
Migration: pin platform floor to Ubuntu 24.04 / glibc 2.38 (drop 22.04 support)

### ISSUE THREAD

**Issue by tosin2013** [tosin2013/aegis-node#157]
Bump the project's default supported Linux platform floor from Ubuntu 22.04 (Jammy) to **Ubuntu 24.04 (Noble)** so:

1. **LiteRT-LM works out-of-the-box** — the prebuilt `libaegis_litertlm_engine_cpu.so` (per ADR-023) requires `glibc ≥ 2.38` + `GLIBCXX_3.4.31` (GCC 13.2+). On Ubuntu 22.04 (glibc 2.35, GLIBCXX caps at 3.4.30) the link step fails with `undefined reference to __isoc23_strtoull@GLIBC_2.38`. Operators on 22.04 can build with `--features llama` only; Gemma 4 family (LiteRT-LM) silently can't run.
2. **CI matrix is honest** — `litertlm.yml` already pins `ubuntu-24.04`; everything else is `ubuntu-latest` which currently resolves to 24.04 but isn't pinned and could drift. Pinning everything to `ubuntu-24.04` makes the floor explicit and prevents the next default flip from surprising us.
3. **Devcontainer matches CI** — `.devcontainer/Dockerfile` is on `ubuntu-22.04` today; contributors using the devcontainer can't reproduce the LiteRT-LM build path locally even though CI does it on 24.04.
4. **Modern tooling assumed** — Vite 6 + Tailwind 4 (per ADR-031's locked stack) work on 22.04 today via NodeSource pinning; on 24.04 they work without the workaround. Doc burden goes down.

## Audit (current state, 2026-05-07)

| Location | Pin | Status |
|---|---|---|
| `.github/workflows/litertlm.yml` | `ubuntu-24.04` | ✓ correct |
| `demos/Dockerfile` | `ubuntu:24.04` | ✓ correct |
| `.github/workflows/rust.yml` | `ubuntu-latest` | currently 24.04, **not pinned** |
| `.github/workflows/llama.yml` | `ubuntu-latest` | currently 24.04, **not pinned** |
| `.github/workflows/demos.yml` (build-renderer + snapshot jobs) | `ubuntu-latest` ×2 | currently 24.04, **not pinned** |
| `.github/workflows/validate.yml` | `ubuntu-latest` | currently 24.04, **not pinned** |
| `.github/workflows/schemas.yml` | `ubuntu-latest` | currently 24.04, **not pinned** |
| `.github/workflows/replay-viewer.yml` | `ubuntu-latest` | currently 24.04, **not pinned** |
| `.github/workflows/models-publish.yml` | `ubuntu-latest` | currently 24.04, **not pinned** |
| `.github/workflows/litertlm-runtime-publish.yml` | `ubuntu-latest` | currently 24.04, **not pinned** |
| `.github/workflows/demos-renderer-publish.yml` | `ubuntu-latest` | currently 24.04, **not pinned** |
| `.devcontainer/Dockerfile` | `mcr.microsoft.com/devcontainers/base:ubuntu-22.04` | **must bump** |

ADR-017 (dev environment) doesn't currently document a platform floor — adding it as an amendment closes the doc gap.

### PR 1: pin all workflows to `ubuntu-24.04`

Single PR: `s/ubuntu-latest/ubuntu-24.04/` across the 9 unpinned workflow runs-on fields. Behaviour-neutral today (latest IS 24.04); makes the floor explicit so future GHA default flips don't auto-bump us.

### PR 2: bump devcontainer + amend ADR-017

- `.devcontainer/Dockerfile`: `mcr.microsoft.com/devcontainers/base:ubuntu-24.04`
- Amend [ADR-017](https://github.com/tosin2013/aegis-node/blob/main/docs/adrs/017-local-development-environment-devcontainer-mise.md) with a "Supported platforms" section spelling out the floor (Ubuntu 24.04 LTS / Debian 13 Trixie / RHEL 10 / Fedora 40+ — anything with glibc ≥ 2.38 + GLIBCXX ≥ 3.4.31), the rationale (LiteRT-LM prebuilt + modern tooling), and the deprecation window for 22.04 (best-effort llama-only; no LiteRT-LM support).
- `docs/CHAT.md` cross-reference to the ADR amendment instead of inlining the glibc detail.

### PR 3 (optional): `.github/workflows/rust.yml` matrix expansion to lock the floor

Add a smoke-test job pinned to `ubuntu-24.04` that verifies Tail-of-22.04 errors don't sneak in (e.g. by accidentally relying on glibc 2.35 symbols). Probably overkill until we have a concrete near-miss.

## Acceptance

- [ ] All workflow `runs-on` lines explicit (`ubuntu-24.04`, not `latest`)
- [ ] Devcontainer base image is `ubuntu-24.04`
- [ ] `.devcontainer` rebuild on a clean checkout produces a container that can `cargo build -p aegis-cli --features "llama litertlm"` cleanly
- [ ] ADR-017 amendment merged
- [ ] `docs/CHAT.md` updated to point at the ADR for the platform-floor rationale
- [ ] README's quickstart section (if any) reflects the floor

## Related

- Operator chat doc: docs/CHAT.md (#156)
- ADR-014 (llama.cpp backend — no platform constraint beyond what cmake/clang need)
- ADR-023 (LiteRT-LM backend — implicit glibc 2.38 requirement, surfaces here)
- ADR-017 (dev environment — gets the amendment)
- v1.0.0 milestone: #134 (multi-turn loop + GA)
- v0.9.5 milestone: #135

## Memory note

Saved as `project_platform_floor_ubuntu_2404.md` — when triaging future build/CI issues, this is the floor to assume.

**Comment by tosin2013** [comment]
## Status update — 2026-05-15

**PR 1** (CI workflow pinning) shipped in [`6f708b1`](../commit/6f708b1) (#158).
**PR 2** (devcontainer bump + ADR-017 platform-floor amendment) shipped in [`9dcd872`](../commit/9dcd872) (#159).

**Next action: PR 3** — add a smoke-test job to `.github/workflows/rust.yml` that verifies the ubuntu-24.04 / glibc-2.38 floor:

- Pinned to `ubuntu-24.04` explicitly.
- Builds with `cargo build -p aegis-cli --features "llama litertlm"` (forces the LiteRT-LM link path that needs `__isoc23_strtoull@GLIBC_2.38`).
- Asserts the built binary's required glibc symbols are `≤ GLIBC_2.38` so we catch accidental forward-symbol drift early.

Closes #157 once PR 3 merges.

**Comment by tosin2013** [comment]
Closing — acceptance audit (2026-05-23):

| Item | Status |
|---|---|
| All workflow `runs-on` lines explicit (`ubuntu-24.04`, not `latest`) | ✅ `grep ubuntu-latest .github/workflows/*.yml` returns nothing; 17 workflows on `ubuntu-24.04` |
| Devcontainer base image is `ubuntu-24.04` | ✅ `.devcontainer/Dockerfile:FROM mcr.microsoft.com/devcontainers/base:ubuntu-24.04` |
| ADR-017 amendment merged | ✅ §"Supported platforms" present, dated 2026-05-07, refs #157 |
| `docs/CHAT.md` points at ADR for floor rationale | ✅ CHAT.md:86-92 |
| README quickstart reflects floor | ✅ README:47 mentions "Ubuntu 22.04/24.04, CentOS 10 family" and links docs/INSTALL.md |
| Devcontainer rebuild produces a container that can `cargo build -p aegis-cli --features "llama litertlm"` | Inferred ✅ — the devcontainer has shipped on ubuntu-24.04 for weeks and CI's litertlm.yml runs the same build on the same image. Not re-verified end-to-end in this audit. |

All migration goals are met; closing as done.
